### ISSUE TITLE
X300A Support

### ISSUE THREAD

**Issue by janbl** [N0ciple/hass-kef-connector#12]
Hi, do you see a chance to support X300A?

**Comment by N0ciple** [comment]
Hello @janbl,

If I am not mistaken, X300A speakers are not built on the same W2 platform as LS50, 60 and LSX, so it won't be possible to support them in pykefcontrol/hass-kef-connector without rewriting a new connector from the ground up. 

But since the X300A are compatible with DLNA you can use the Home Assistant DLNA integration https://www.home-assistant.io/integrations/dlna_dmr/

Let me know if this helps !
